tasks:
  # Process:
  - source: tasks.get.get_bronchiolitis_locations
    params:
      ENV_MEDICAL_RECORDS_CSV_PATH: '{{root_path}}{{bronchiolitis_cases_file_path}}' 
      ENV_ADRESSES_AND_LATLONG_CSV_PATH: '{{root_path}}{{adresses_file_path}}' 
    product: _products/get/bronchiolitis_points.parquet

  - source: tasks.get.get_shape
    params:
      PUERTO_MADRYN_SHAPEFILE_PATH: '{{root_path}}{{puerto_madryn_shapefile}}' 
    product: _products/get/pm_shape.parquet

  - source: tasks.get.get_nbi
    params:
      PUERTO_MADRYN_SHAPEFILE_PATH: '{{root_path}}{{puerto_madryn_shapefile}}' 
    product: _products/get/nbi.parquet

  - source: tasks.cases.get_cases_for_each_circuit
    params:
      PUERTO_MADRYN_SHAPEFILE_PATH: '{{root_path}}{{puerto_madryn_shapefile}}' 
    product: _products/cases/bronchiolitis_and_tracts.parquet

  - source: tasks.spatial.get_moranplot
    params:
      LABEL_BY_QUADFILTER_DICT: '{{label_by_quadfilter}}'
      COLOR_BY_LABELNAME_DICT: '{{color_by_labelname}}'
      KNN_VALUE: '{{knn_k}}'
    product:
      cluster_labels: _products/spatial/cluster_labels.parquet
      moranplot: _products/spatial/moranplot.png

  - source: tasks.spatial.get_moranplot_bv
    params:
      LABEL_BY_QUADFILTER_DICT: '{{label_by_quadfilter}}'
      COLOR_BY_LABELNAME_DICT: '{{color_by_labelname}}'
      KNN_VALUE: '{{knn_k}}'
    product:
      cluster_labels: _products/spatial/cluster_labels_bv.parquet
      moranplot: _products/spatial/moranplot_bv.png

  #
  - source: tasks.nbi_map.get_nbi_clusters
    product: _products/nbi/nbi_clusters.parquet

  - source: tasks.nbi_map.get_nbi_map
    product: _products/nbi/nbi_map.png

  # Figures:
  - source: tasks.clustermap.get_cluster_figure
    name: clustermap_figure
    params:
      PUERTO_MADRYN_BASEMAP_TIF_PATH: '{{root_path}}{{puerto_madryn_basemap_file}}' 
      SOUTH_AMERICA_BASEMAP_TIF_PATH: '{{root_path}}{{south_america_basemap_file}}'
      LABEL_BY_QUADFILTER_DICT: '{{label_by_quadfilter}}'
      PAINT_BRONCHIOLITIS_LOCATIONS_IN_MAP: '{{paint_bronchiolitis_locations_in_map}}'
      DIFFERENTIATE_ADMISSIONS_AND_READMISSIONS: '{{differentiate_admissions_and_readmissions}}'
    product: _products/cluster/cluster_map.png

  - source: tasks.clustermap.get_cluster_figure_bv
    name: clustermap_figure_bv
    params:
      PUERTO_MADRYN_BASEMAP_TIF_PATH: '{{root_path}}{{puerto_madryn_basemap_file}}' 
      SOUTH_AMERICA_BASEMAP_TIF_PATH: '{{root_path}}{{south_america_basemap_file}}' 
      LABEL_BY_QUADFILTER_DICT: '{{label_by_quadfilter}}'
      PAINT_BRONCHIOLITIS_LOCATIONS_IN_MAP: '{{paint_bronchiolitis_locations_in_map}}'      
    product: _products/cluster/cluster_bv_map.png

  # Report:
  - source: tasks.report.create_report
    params:
      KNN_VALUE: '{{knn_k}}'
    product: _output/report.pdf